CommerceBank/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using CommerceBank.Datas;
using CommerceBank.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using CommerceBank.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;
using System;

namespace CommerceBank.Controllers
{

    [Authorize]
    public class NotificationController : Controller
    {
        float total = 0;
        private TransactionContext _Context;
        private readonly INotification _Repo;
        private readonly ITransaction _TransRepo;
        private readonly UserManager<ApplicationUser> _userManager;

        public NotificationController(ITransaction repoT, INotification repo, UserManager<ApplicationUser> userManager, TransactionContext Context)
        {
            _Context = Context;
            _userManager = userManager;
            _Repo = repo; //direct to the constructor in the file "TransactionRepositories" (Benjamin Nguyen)
            _TransRepo = repoT; 
        }



        public IActionResult Index(string sortExpression = "", string Search = "")
        {

            dynamic dy = new ExpandoObject();
            dy.notilist = GetNoti(sortExpression, Search);
            dy.translist = GetTrans(sortExpression, Search);
            return View(dy);
        }
    
        public List<Transaction> GetTrans(string sortExpression, string Search)
        {
            
            SortModels sortModel = new SortModels();
            sortModel.AddColumn("location");
            sortModel.AddColumn("balancetype");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            List<Transaction> trans = _TransRepo.GetItems(sortModel.SortedProperty, sortModel.SortedTransaction);
            return trans;
        }
        public List<Notifica> GetNoti(string sortExpression, string Search)
        {
            SortModels sortModel = new SortModels();
            sortModel.AddColumn("location");
            sortModel.AddColumn("balancetype");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            List<Notifica> noti = _Repo.GetItems(sortModel.SortedProperty, sortModel.SortedTransaction, Search);
            return noti;
        }


        //---------------------------- CREATE NEW TRANSACTION PART ----------------------------//
        [HttpGet]
        public IActionResult Create()
        {
            Notifica noti = new Notifica();
            return View(noti);
        }

        [HttpPost]
        public IActionResult Create(Notifica noti)
        {
            int count = 0;
            
            try
            {
                
                 //List<Transaction> Transs = _Context.Transac.ToList();
                //Transs = _Context.Transac.OrderBy(n => n.UserKey).ToList();
                noti.UserKey = _userManager.GetUserId(HttpContext.User);
                noti.CreatedDate = DateTime.Now;
                //Trans.Balance = Transs.LastOrDefault(d => d.UserKey == userId).Balance - Trans.Amount;





                _Repo.Create(noti); //direct to the method "create" in the file "TransactionRepositories" (Benjamin Nguyen)
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }


        //---------------------------- TRANSACTION DETAIL PART ----------------------------//
        public IActionResult Details(int id)
        {
            Transaction noti = _TransRepo.GetTransaction(id);
            return View(noti);

        }




        //---------------------------- EDIT TRANSACTION PART ----------------------------//
        public IActionResult Edit(int id)
        {
            Notifica noti = _Repo.GetNotification(id);
            return View(noti);

        }
        [HttpPost]
        public IActionResult Edit(Notifica noti)
        {
            try
            {
                _Repo.Edit(noti);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }


        //---------------------------- DELETE TRANSACTION PART ----------------------------//
        public IActionResult Delete(int id)
        {
            Notifica Trans = _Repo.GetNotification(id);
            return View(Trans);

        }
        [HttpPost]
        public IActionResult Delete(Notifica noti)
        {
            try
            {
                //_Context.Transac.Attach(Trans);
                //_Context.Entry(Trans).State = EntityState.Deleted; // tell the EFCore that this entry needs to be updated
                //_Context.SaveChanges();
                noti = _Repo.Delete(noti); //Step 4
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }

    }
}

CommerceBank/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using CommerceBank.Datas;
using CommerceBank.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using CommerceBank.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CommerceBank.Controllers
{
    
    [Authorize]
    public class TransactionController : Controller
    {
        float total = 0;
        private  TransactionContext _Context;
        private readonly ITransaction _TransactionRepo;
        private readonly UserManager<ApplicationUser> _userManager;

        public TransactionController(ITransaction transrepo, UserManager<ApplicationUser> userManager, TransactionContext Context)
        {
            _Context = Context;
            _userManager = userManager;
            _TransactionRepo = transrepo; //direct to the constructor in the file "TransactionRepositories" (Benjamin Nguyen)
        }

        

        public IActionResult Index(string sortExpression= "")
        {

            SortModels sortModel = new SortModels();
            sortModel.AddColumn("location");
            sortModel.AddColumn("balancetype");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"]=sortModel;

            List<Transaction> Trans = _TransactionRepo.GetItems(sortModel.SortedProperty, sortModel.SortedTransaction); 
            return View(Trans);
         }
        private List<StatesList> GetState()
        {
            var state = new List<StatesList>();
            state.Add(new StatesList() { id = 1, State = "MO" });

            return state;
        }




        //---------------------------- CREATE NEW TRANSACTION PART ----------------------------//
        [HttpGet]
        public IActionResult Create()
        {
            Transaction Trans = new Transaction();
            return View(Trans);
        }

        [HttpPost]
        public IActionResult Create(Transaction Trans)
        {
            int count = 0;
            ViewBag.StateSelectList = new SelectList(GetState(), "id", "state");
            try
            {
                string userId = _userManager.GetUserId(User);
                foreach (var item in _Context.Transac)
                {
                    if (item.UserKey == _userManager.GetUserId(HttpContext.User))
                    {
                        count+=1;
                    }
                }
                if (count == 0 || _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance == 0)
                {
                    Trans.UserKey = _userManager.GetUserId(HttpContext.User);
                    Trans.Balance = _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance + Trans.Amount;
                    _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance = Trans.Balance;


                    Trans.BalanceType = "Deposit";
           
     
                }
            

                else
                {
                    if (Trans.BalanceType == "Deposit")
                    {
                        if (Trans.Amount == 0)
                        {
                            
                            return RedirectToAction("Create");
                        }
                        else
                        {
                            Trans.Balance = _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance + Trans.Amount;
                        }    
                        
                    }
                    else if (Trans.BalanceType == "Withdraw")
                    {
                        if ( _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance - Trans.Amount <0 || Trans.Amount == 0)
                        {
                            ViewBag.ErrorMessage = "not enough";
                            return RedirectToAction("Create");
                        }
                        else
                        {
                            Trans.Balance = _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance - Trans.Amount;
                        }
                        
                    }
                    //List<Transaction> Transs = _Context.Transac.ToList();
                    //Transs = _Context.Transac.OrderBy(n => n.UserKey).ToList();
                    Trans.UserKey = _userManager.GetUserId(HttpContext.User);
                    //Trans.Balance = Transs.LastOrDefault(d => d.UserKey == userId).Balance - Trans.Amount;
                    
                    _userManager.Users.FirstOrDefault(u => u.Id == userId).TotalBalance = Trans.Balance;
                }
                
                
                _TransactionRepo.Create(Trans); //direct to the method "create" in the file "TransactionRepositories" (Benjamin Nguyen)
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }


        //---------------------------- TRANSACTION DETAIL PART ----------------------------//
        public IActionResult Details(int id)
        {
            Transaction Trans = _TransactionRepo.GetTransaction(id);
            return View(Trans);

        }

        


        //---------------------------- EDIT TRANSACTION PART ----------------------------//
        public IActionResult Edit(int id)
        {
            Transaction Trans = _TransactionRepo.GetTransaction(id);
            return View(Trans);

        }
        [HttpPost]
        public IActionResult Edit(Transaction Trans)
        {
            try
            {
                _TransactionRepo.Edit(Trans);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }


        //---------------------------- DELETE TRANSACTION PART ----------------------------//
        public IActionResult Delete(int id)
        {
            Transaction Trans = _TransactionRepo.GetTransaction(id);
            return View(Trans);

        }
        [HttpPost]
        public IActionResult Delete(Transaction Trans)
        {
            try
            {
                //_Context.Transac.Attach(Trans);
                //_Context.Entry(Trans).State = EntityState.Deleted; // tell the EFCore that this entry needs to be updated
                //_Context.SaveChanges();
                Trans = _TransactionRepo.Delete(Trans); //Step 4
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }

    }
}

CommerceBank/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CommerceBank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!--<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CommerceBank</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notification" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                            </li>
                            
                        }
                             
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>

                    <partial name= "_LoginPartial" />

                </div>
            </div>
        </nav>
    </header> -->
    <header class="border-top header text-muted">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container justify-content-start">
                <!--<a class="navbar-brand" asp-area="" asp-page="/Index"><img src="/images/Inverse Logo.png" style="width:50%"></a>
                !<div class="myBankNameDiv">
                    <h3> Commerce Bank </h3>
                </div> 
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CommerceBank</a>-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li><a asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/Inverse Logo.png" style="width:65%" /></a> </li>

                        <!--<li><a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CommerceBank</a></li> -->
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Notification" asp-action="Index">Notifications</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Transaction" asp-action="Index">Transaction</a>
                            </li>
                            
                        }
                             
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>

                    <partial name= "_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <!--<div class="container">
            &copy; 2022 - CommerceBank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>-->
        <nav class="footer-nav">
            <ul>
                <li><a href="about-us.html">About Us</a> </li>
                <li><a href="contact.html">Contact</a> </li>
            </ul>
        </nav>

        <nav class ="footer-nav-2">
                <ul>
                    <li><a href="facebook-placeholder.html"><img src="/images/Facebook.png" 
                        width="30" height="30" style="margin:0px 5px;" 
                        class= "img" alt="Facebook" /></a> </li>

                    <li><a href="twitter-placeholder.html"><img src="/images/Twitter.png"
                        width="30" height="30" style="margin:0px 5px;" 
                        class= "img" alt="Twitter" /></a> </li>

                    <li><a href="instagram-placeholder.html"><img src="/images/Instagram.png"
                        width="30" height="30" style="margin:0px 5px;" 
                        class= "img" alt="Instagram" /></a> </li>

                    <li><a href="linkedin-placeholder.html"><img src="/images/LinkedIn.png"
                        width="30" height="30" style="margin:0px 5px;" 
                        class= "img" alt="LinkedIn" /></a> </li>
                </ul>
        </nav>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>